server:
  port: 8071

spring:
  application:
    name: star-auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star?characterEncoding=UTF-8&serverTimezone=UTC
    username: neo
    password: IAMneo
    type: com.alibaba.druid.pool.DruidDataSource