server:
  port: 8081

spring:
  application:
    name: star-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star?characterEncoding=UTF-8&serverTimezone=UTC
    username: neo
    password: IAMneo
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
